// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpnidgnugwfubsxfprbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbmlkZ251Z3dmdWJzeGZwcmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDEwNDMsImV4cCI6MjA1ODM3NzA0M30.KwtuwPZCZTDnT9RAjIOYKhNraA0yQM-wkcKvKeRm3PQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);